[build]
  command = "npm run build"
  publish = "out"  # Certifique-se de que isso está correto

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18.20.0"
  NPM_VERSION = "10.8.2"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 